export const ADD_TASK = "ADD_TASK";
export const ADD_COLUMN = "ADD_COLUMN";
export const REARANGE_COLUMN = "REARANGE_COLUMN";
export const REARANGE_KANBAN = "REARANGE_KANBAN";
export const SHIFT_COLUMN = "SHIFT_COLUMN";